name: CI basic

# Déclenchement sur push et PR
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Vérifier l’app
        run: bash app/check_app.sh
